# Specify API Version For PersistentVolumeClaim Object = v1
# Specify Kind/Type of Object = PersistentVolumeClaim
# Metadata = Name of PersistentVolumeClaim
# Spec will specify the AccessModes = ReadWriteOnce
# Resoources to specify the storage volume size request = 2Gi

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi